version: '3.8'
services:
  app:
    container_name: app
    build: .
    ports:
      - 3300:3300
    env_file: .env
    depends_on: 
      - postgres

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:13
    ports:
      - 5432:5432
    restart: always
    env_file: .env
